version: '3'
services:
  app:
    image: node:18
    working_dir: /app
    ports:
      - '3000:3000'
    depends_on:
      - rabbitmq
      - mongodb
    env_file:
      - ./src/config/.env
    volumes:
      - .:/app
    command: npm start

  rabbitmq:
    image: rabbitmq:latest
    ports:
      - '5672:5672'
      - '15672:15672'

  mongodb:
    image: mongo:latest
    ports:
      - '27017:27017'
    volumes:
      - mongodb_data:/data/db

volumes:
  mongodb_data: